name: lembrei_pegar
description: "A new Flutter project."

publish_to: 'none' # Não publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Plugins
  android_alarm_manager_plus: ^4.0.7
  firebase_messaging: ^14.9.4
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  uuid: ^4.0.0
  google_fonts: ^6.1.0
  collection: ^1.17.0

  # Firebase
  firebase_core: ^2.28.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.5

  # Notificações Locais
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Se quiser usar outras imagens no app, ative:
  # assets:
  #   - assets/

# Configuração do plugin flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # Caminho atualizado da sua imagem
  min_sdk_android: 21
  # Para ícones adaptativos (opcional), descomente e crie um foreground separado:
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/icon/icon_foreground.png"
