// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJB9InOWaQkOTih7lDLAxEqQDyEV-xbdQ',
    appId: '1:187950668823:web:a10eae7cbebf5c2003d052',
    messagingSenderId: '187950668823',
    projectId: 'lembrei-de-pagar',
    authDomain: 'lembrei-de-pagar.firebaseapp.com',
    storageBucket: 'lembrei-de-pagar.firebasestorage.app',
    measurementId: 'G-YLLCD1CN1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLuO20bWXr-aFGkSlCIYiJQeV65i8ygNw',
    appId: '1:187950668823:android:3d0286f785d13bb303d052',
    messagingSenderId: '187950668823',
    projectId: 'lembrei-de-pagar',
    storageBucket: 'lembrei-de-pagar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbl0UGYYR_KtR1kNfDrwkULhncX_GqhXE',
    appId: '1:187950668823:ios:0e6fd71caff9de4703d052',
    messagingSenderId: '187950668823',
    projectId: 'lembrei-de-pagar',
    storageBucket: 'lembrei-de-pagar.firebasestorage.app',
    androidClientId: '187950668823-e2vr5ehi2i25kcua1c0l8ma26pql86fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.lembreiPegar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbl0UGYYR_KtR1kNfDrwkULhncX_GqhXE',
    appId: '1:187950668823:ios:0e6fd71caff9de4703d052',
    messagingSenderId: '187950668823',
    projectId: 'lembrei-de-pagar',
    storageBucket: 'lembrei-de-pagar.firebasestorage.app',
    androidClientId: '187950668823-e2vr5ehi2i25kcua1c0l8ma26pql86fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.lembreiPegar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJB9InOWaQkOTih7lDLAxEqQDyEV-xbdQ',
    appId: '1:187950668823:web:baa621eae1f79cf703d052',
    messagingSenderId: '187950668823',
    projectId: 'lembrei-de-pagar',
    authDomain: 'lembrei-de-pagar.firebaseapp.com',
    storageBucket: 'lembrei-de-pagar.firebasestorage.app',
    measurementId: 'G-P4Y8TKDCQH',
  );

}